name: tf1_env
channels:
  - defaults
dependencies:
  - certifi=2021.5.30
  - pip=21.2.2
  - python=3.6.13
  - setuptools=58.0.4
  - sqlite=3.50.2
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.37.1
  - wincertstore=0.2
  - pip:
      - bleach==1.5.0
      - dataclasses==0.8
      - h5py==2.7.1
      - html5lib==0.9999999
      - importlib-metadata==4.8.3
      - keras==2.0.8
      - markdown==3.3.7
      - numpy==1.13.3
      - olefile==0.47
      - pandas==0.18.0
      - pillow==4.2.1
      - protobuf==3.19.6
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.1
      - scikit-learn==0.19.0
      - scipy==1.4.1
      - six==1.17.0
      - tensorflow==1.3.0
      - tensorflow-tensorboard==0.1.8
      - typing-extensions==4.1.1
      - werkzeug==2.0.3
      - zipp==3.6.0
prefix: D:\Software\MiniConda\envs\tf1_env
